---
- name: 'Start and enable the apache2 service'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.start_and_or_enable_systemd_service'
      service_name: 'apache2'
      service_started: true
      service_enabled: true
