---
- name: 'Configure apache2 for LDAP'
  hosts: 'all'
  gather_facts: true
  become: true


  tasks:

    - name: 'Fail if required LDAP settings are not provided'
      ansible.builtin.fail:
        msg: "{{ item }} is not defined, aborting..."
      when:
        - hostvars[inventory_hostname][item] is undefined
      loop:
        - 'ldap_server_url'
        - 'ldap_binddn_name'
        - 'ldap_binddn_password'

    - name: 'Create directories'
      ansible.builtin.file:
        path: "{{ item }}"
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'
      loop:
        - '/srv/www/vhosts/'
        - '/srv/www/vhosts/apache-server/'
        - '/srv/www/vhosts/apache-server/basicauth'
        - '/srv/www/vhosts/apache-server/ldap'
        - '/srv/www/vhosts/apache-server/secret'

    - name: 'Create file index.html in public directory'
      ansible.builtin.copy:
        content: |
          This is the public directory

        dest: '/srv/www/vhosts/apache-server/index.html'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Create file index.html in secret directory'
      ansible.builtin.copy:
        content: |
          This is the secret directory

        dest: '/srv/www/vhosts/apache-server/secret/index.html'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Create file index.html in basicauth directory'
      ansible.builtin.copy:
        content: |
          This is the basicauth directory

        dest: '/srv/www/vhosts/apache-server/basicauth/index.html'
        owner: 'root'
        group: 'root'
        mode: '0644'

    - name: 'Create file index.html in ldap directory'
      ansible.builtin.copy:
        content: |
          This is the ldap directory

        dest: '/srv/www/vhosts/apache-server/ldap/index.html'
        owner: 'root'
        group: 'root'
        mode: '0644'

    #
    # Basic Authentication
    #
    - name: 'Create file /etc/apache2/htpasswd'
      ansible.builtin.shell:
        cmd: 'echo vagrant-ansible-libvirt | /usr/bin/htpasswd -c -i /etc/apache2/htpasswd vagrant-ansible-libvirt'
        creates: '/etc/apache2/htpasswd'

    #
    # LDAP Authentication
    #
    - name: 'Enable apache module '
      ansible.builtin.lineinfile:
        path: '/etc/sysconfig/apache2'
        # regexp: '^APACHE_MODULES="(.*)(\smod_ldap.*){0,1}"$'
        # line: 'APACHE_MODULES="\1 mod_ldap mod_authnz_ldap"'
        # backrefs: true
        regexp: '^APACHE_MODULES=".*"$'
        line: 'APACHE_MODULES="actions alias auth_basic authn_core authn_file authz_host authz_groupfile authz_core authz_user autoindex cgi dir env expires include log_config mime negotiation setenvif ssl socache_shmcb userdir reqtimeout ldap authnz_ldap"'
      notify:
        - 'Restart apache2.service'

    #
    # vhost definition
    #
    - name: 'Create vhost-ldap-test.conf'
      ansible.builtin.template:
        src: 'vhost-ldap-test.conf.j2'
        dest: '/etc/apache2/vhosts.d/vhost-ldap-test.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      notify:
        - 'Restart apache2.service'

  handlers:

    - name: 'Restart apache2.service'
      ansible.builtin.service:
        name: 'apache2'
        state: 'restarted'
